### ISSUE TITLE
PTR records resolve

### ISSUE THREAD

**Issue by scopenco** [skx/dns-api-go#8] opened 2018-10-28 22:20 UTC
Hello,

PTR records resolving doesn't looks like native. 
```
# curl http://127.0.0.1:9999/PTR/87.250.250.242
{
     "error": "NXDOMAIN"
}
```
but should return `ya.ru`.

If i try to use 
```
# curl http://127.0.0.1:9999/PTR/242.250.250.87.in-addr.arpa
[
     {
          "name": "242.250.250.87.in-addr.arpa.",
          "ttl": "273",
          "type": "PTR",
          "value": "ya.ru."
     }
```
it works but i need to changes my request.   
All modern tools are using first example as native. What do you think do change this behavior like first one?

**Comment by skx** [comment] 2018-10-29 03:39
This is a duplicate of #5, which is [addressed in the README.md](https://github.com/skx/dns-api-go#notes) file to avoid confusion.

If this were a command-line application where humans were expected to use it then I'd agree, and add the rewriting support.  However this is an API designed to be consumed by computers, and for that reason I think I should assume they know why they're calling it, and what they're doing.

I believe the current behaviour is mostly "correct", though I think I should probably return an error such as:

       # curl http://127.0.0.1:9999/PTR/87.250.250.242
       {
            "error": "Invalid input format"
       }

**Comment by pooja-chauhan** [comment] 2020-04-16 07:24
getting below error on installing:
Step 3/8 : RUN go get -u github.com/skx/dns-api-go
 ---> Running in dcfcfa837eff
# github.com/skx/dns-api-go
root/go/src/github.com/skx/dns-api-go/main.go:313:38: rateLimiter.AllowHour undefined (type *redis_rate.Limiter has no field or method AllowHour)

**Comment by skx** [comment] 2020-04-16 11:59
Please open a new issue to describe a new problem.

It seems that the version of the rate-limiter I'm using has changed their API.  There seem to be three solutions:

* Download a binary release, and ignore the problem:
  * https://github.com/skx/dns-api-go/releases
* Update the code to remove the rate-limiter.
* Update the code to work with the [new rate-limiter API](https://github.com/go-redis/redis_rate).

Since the service was abused so much I would probably not be interested in making further changes myself, I'd probably be willing to remove the code though if that is useful.

**Closed by skx** 2020-04-16 11:59 UTC
Labels: documentation, duplicate
